### ISSUE TITLE
Add Note that this applies to Exchange Classic View

### ISSUE THREAD

**Issue by mhparker44** [NetAppDocs/saasbackupO365#112]
Page: [Configuring Impersonation for  Microsoft Exchange Online](https://docs.netapp.com/us-en/saasbackupO365/task_configuring_impersonation.html)

Can we please add a note that these apply to the Classic View of Exchange Admin Center. After step 2.

How to change to Classic View: Click "Classic Exchange Admin Center" from the left menu.
![EAC](https://user-images.githubusercontent.com/51545450/108266440-1affa180-7138-11eb-824b-2cb71e78e7d8.jpg)

Also note: "For now, it is possible to switch back to the existing EAC (often called the "classic" EAC), but at a future date, the classic EAC will be retired."  - https://docs.microsoft.com/en-us/exchange/whats-new
Eventually we will need to update the docs.

**Comment by netapp-rlithman** [comment]
Hi Matthew. Thanks for sharing your issue with us. As I understand it, this issue relates to the Microsoft UI rather than the NetApp SaaS Backup UI. We include a limited amount of documentation specific to Microsoft's UI. This may fall out of our scope. I'm going to follow up with you via email to learn more about it.
